#!/usr/bin/env bash
# BE Digital customer website — Cloud Agent install (idempotent).
#
# Reusable pattern for any BE Digital customer website repository:
#   CUSTOMER WEBSITE            (primary work repo — this repository)
#   + BE Digital CMS repo       (reference / platform context)
#   + BE Digital architecture   (reference / docs context)
#
# The DEFAULT startup installs only this website and prepares safe dev/preview config.
# It does NOT start a local CMS or PostgreSQL — see .cursor/local-fullstack.sh for that
# (opt-in) — and it never writes to the production CMS (https://cms.bedigital.ai).
set -euo pipefail

SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SITE_DIR"

# Workspace root where sibling repos live (repositoryDependencies check them out here).
WORKSPACE_ROOT="$(cd "$SITE_DIR/.." && pwd)"

# Ensure a package manager is available (default cloud image ships pnpm; fall back to corepack).
if ! command -v pnpm >/dev/null 2>&1; then
  corepack enable pnpm >/dev/null 2>&1 || true
fi

echo "[install] Installing website dependencies (pnpm)…"
pnpm install --frozen-lockfile

# Make the BE Digital platform + architecture repos available for inspection/reference.
# repositoryDependencies (see environment.json) normally checks these out next to this repo;
# clone them read-only as a fallback so reference context is always present.
ensure_reference_repo() {
  local name="$1" url="$2"
  if [ -d "$WORKSPACE_ROOT/$name/.git" ]; then
    echo "[install] Reference repo present: $name"
  else
    echo "[install] Cloning reference repo: $name"
    git clone --depth 1 "$url" "$WORKSPACE_ROOT/$name" \
      || echo "[install] WARN: could not clone $name (may be provided at runtime)."
  fi
}
ensure_reference_repo "Be-digital-cms" "https://github.com/Bedigital-cms/Be-digital-cms"
ensure_reference_repo "bedigital-architecture" "https://github.com/BEBarry/bedigital-architecture"

# Safe development/preview defaults — never write to the production CMS by default.
# Media keeps loading read-only from the production CMS (cms.bedigital.ai, via .env);
# form submissions are disabled locally so ordinary development never POSTs to production.
if [ ! -f .env.local ]; then
  echo "[install] Writing safe .env.local (form submissions disabled locally)…"
  cat > .env.local <<'EOF'
# Safe local/preview overrides — generated by the Cloud Agent environment (.env.local is gitignored).
# Media still loads read-only from the production CMS (cms.bedigital.ai) via .env; form submissions
# are disabled here so normal development/preview never writes to the production CMS.
# For a full local stack (local CMS + PostgreSQL), run: bash .cursor/local-fullstack.sh
NEXT_PUBLIC_FORMS_ENDPOINT=
EOF
else
  echo "[install] .env.local already present — leaving it untouched."
fi

echo "[install] Done. The website dev server runs via the 'izzi-web' terminal (pnpm dev --port 3001)."
