#!/usr/bin/env bash
# OPTIONAL local full-stack mode — NOT part of the default Cloud Agent startup.
#
# Brings up the complete BE Digital stack locally for the rare tasks that genuinely need it:
#   - Be-digital-cms (Payload CMS)   on http://localhost:3000
#   - its PostgreSQL dependency        (installed + seeded by the CMS repo's own scripts)
#   - this customer website            on http://localhost:3001, pointed at the LOCAL CMS
#
# Usage (run manually from the website repo root):
#   bash .cursor/local-fullstack.sh
#
# This points media/forms at the LOCAL CMS via .env.local, so it still never touches the
# production CMS (https://cms.bedigital.ai). Press Ctrl-C to stop everything. To return to the
# default safe mode afterwards, remove .env.local and re-run: bash .cursor/install.sh
set -euo pipefail

SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_ROOT="$(cd "$SITE_DIR/.." && pwd)"
CMS_DIR="$WORKSPACE_ROOT/Be-digital-cms"

if [ ! -d "$CMS_DIR/.git" ]; then
  echo "[full-stack] Cloning Be-digital-cms…"
  git clone https://github.com/Bedigital-cms/Be-digital-cms "$CMS_DIR"
fi

echo "[full-stack] Bootstrapping CMS (PostgreSQL + deps + seed)…"
bash "$CMS_DIR/.cursor/install.sh"
bash "$CMS_DIR/.cursor/start.sh"

echo "[full-stack] Pointing this site at the LOCAL CMS via .env.local…"
cat > "$SITE_DIR/.env.local" <<'EOF'
# LOCAL FULL-STACK overrides — generated by .cursor/local-fullstack.sh (.env.local is gitignored).
# Points media + forms at the local CMS on :3000 instead of the production CMS.
MEDIA_PUBLIC_BASE=http://localhost:3000/media
NEXT_PUBLIC_FORMS_ENDPOINT=http://localhost:3000
EOF

echo "[full-stack] Starting CMS (:3000) and website (:3001). Ctrl-C to stop…"
(cd "$CMS_DIR" && pnpm dev) &
(cd "$SITE_DIR" && pnpm dev --port 3001) &
wait
