#!/usr/bin/env bash
# OPTIONAL local full-stack mode — NOT part of the default Cloud Agent startup.
#
# Brings up the complete BE Digital stack locally for the rare tasks that genuinely need it:
#   - PostgreSQL                        (installed + started by the CMS repo's own install script)
#   - Be-digital-cms (Payload CMS)      on http://localhost:3000
#   - this customer website             on http://localhost:3001, pointed at the LOCAL CMS
#
# Usage (run manually from the website repo root):
#   bash .cursor/local-fullstack.sh
#
# It points media/forms at the LOCAL CMS via .env.local, so it still never touches the production
# CMS (https://cms.bedigital.ai). Press Ctrl-C to stop both servers. To return to the default safe
# mode afterwards, just re-run the environment install (it deterministically restores the safe
# .env.local): bash .cursor/install.sh
#
# Design notes (verified against Be-digital-cms/.cursor/*):
#   - Be-digital-cms/.cursor/install.sh is the FULL, idempotent CMS bootstrap: it installs
#     PostgreSQL + Node deps, generates Payload types, writes the CMS .env.local, starts the
#     PostgreSQL cluster and creates/seeds the database. It does NOT start the Next.js app.
#   - We therefore run that bootstrap exactly once (it already brings PostgreSQL up, so we do not
#     also call the CMS start.sh — that would be redundant), then start the CMS app and the website
#     exactly once each, in parallel, so neither blocks the other.
set -euo pipefail

SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_ROOT="$(cd "$SITE_DIR/.." && pwd)"
CMS_DIR="$WORKSPACE_ROOT/Be-digital-cms"

if [ ! -d "$CMS_DIR/.git" ]; then
  echo "[full-stack] Cloning Be-digital-cms…"
  git clone https://github.com/Bedigital-cms/Be-digital-cms "$CMS_DIR"
fi

echo "[full-stack] Bootstrapping CMS + PostgreSQL (idempotent)…"
bash "$CMS_DIR/.cursor/install.sh"

echo "[full-stack] Pointing this site at the LOCAL CMS via .env.local…"
cat > "$SITE_DIR/.env.local" <<'EOF'
# LOCAL FULL-STACK overrides — generated by .cursor/local-fullstack.sh (.env.local is gitignored).
# Points media + forms at the local CMS on :3000 instead of the production CMS.
# Re-run `bash .cursor/install.sh` to restore the safe default (production media, forms disabled).
MEDIA_PUBLIC_BASE=http://localhost:3000/media
NEXT_PUBLIC_FORMS_ENDPOINT=http://localhost:3000
EOF

echo "[full-stack] Starting CMS (:3000) and website (:3001). Press Ctrl-C to stop both…"
(cd "$CMS_DIR" && pnpm dev) &
CMS_PID=$!
(cd "$SITE_DIR" && pnpm dev --port 3001) &
SITE_PID=$!

# Clean shutdown: stop both dev servers on Ctrl-C / termination.
trap 'echo "[full-stack] Stopping…"; kill "$CMS_PID" "$SITE_PID" 2>/dev/null || true' INT TERM

# Stay attached until a server exits (or Ctrl-C).
wait
